[package]
name = 'rgrep'
version = '0.1.0'
edition = '2021'

[dependencies]
thiserror = '1.0'
anyhow = '1.0'
glob = '0.3'

[dependencies.clap]
version = '4'
features = ['derive']

[dependencies.tokio]
version = '1'
features = ['full']
